name: CI Pipeline

on: 
    push:
        branches: [main,feature/*]
    pull_request:
        branches: [main]
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: node:18

    env:
      MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}


    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
