name: node js ci pipeline
on:
  push:
    branches: 
        - main
        - 'feature/*'
  pull_request:
    branches:
        - main

  workflow_dispatch:
    inputs:
        logLevel:
            description: 'Log level'
            required: true
            default: 'warning'
            type: choice
            options:
            - info
            - warning
            - debug
        tags:
            description: 'Test scenario tags'
            required: false
            type: boolean
env:
    MONGO_URI: mongodb+srv://cluster0.5hbgafe.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME}}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}


jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            node-version: [18]
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            - name: npm install and build
              run: npm install
            - name: test npm
              run: npm test
            


