name: CI Pipeline

on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017

    env:
      MONGO_URI: mongodb+srv://supercluster.d83jj.mongodb.net/superData
      MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
      MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache node modules
      id: cache-npm
      uses: actions/cache@v3
      env:
        cache-name: cache-node-modules
      with:
        path: node_modules
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }}


    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test
